/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.carloscarbajorua.dein2021.javaswing.ejercicios00;

/**
 *
 * @author Alumno Tarde
 */
public class HolaSwing extends javax.swing.JFrame {

    /**
     * Creates new form HolaSwing
     */
    public HolaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        etiqHolaMundo = new javax.swing.JLabel();
        jButPulsa = new javax.swing.JButton();
        barraMenus = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItArchivoNuevo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItArchivoAbrir = new javax.swing.JMenuItem();
        menuItArchivoGuardar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItSalirAplicacion = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqHolaMundo.setText("¡Hola mundo!");

        jButPulsa.setText("!Pulsa aquí!");
        jButPulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPulsaActionPerformed(evt);
            }
        });

        menuArchivo.setText("Archivo");

        menuItArchivoNuevo.setText("Nuevo");
        menuItArchivoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItArchivoNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItArchivoNuevo);
        menuArchivo.add(jSeparator2);

        menuItArchivoAbrir.setText("Abrir...");
        menuItArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItArchivoAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItArchivoAbrir);

        menuItArchivoGuardar.setText("Guardar");
        menuItArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItArchivoGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItArchivoGuardar);
        menuArchivo.add(jSeparator3);

        menuItSalirAplicacion.setText("Salir");
        menuItSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItSalirAplicacionActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItSalirAplicacion);

        barraMenus.add(menuArchivo);

        menuEditar.setText("Editar");
        barraMenus.add(menuEditar);

        menuAcercaDe.setText("Acerca de...");
        menuAcercaDe.setToolTipText("Información sobre la aplicación");
        menuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDeMouseClicked(evt);
            }
        });
        barraMenus.add(menuAcercaDe);

        setJMenuBar(barraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButPulsa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(etiqHolaMundo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(etiqHolaMundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(jButPulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButPulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPulsaActionPerformed
        jButPulsa.setText("Me has pulsado");
    }//GEN-LAST:event_jButPulsaActionPerformed

    private void menuItArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItArchivoAbrirActionPerformed
        etiqHolaMundo.setText("Has abierto un archivo, ¡¡¡Muy bien!!!");
    }//GEN-LAST:event_menuItArchivoAbrirActionPerformed

    private void menuAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDeMouseClicked
       etiqHolaMundo.setText("Aplicación demo de Swing");
    }//GEN-LAST:event_menuAcercaDeMouseClicked

    private void menuItArchivoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItArchivoNuevoActionPerformed
        etiqHolaMundo.setText("Has creado un nuevo archivo, ¡¡¡Muy bien!!!");
    }//GEN-LAST:event_menuItArchivoNuevoActionPerformed

    private void menuItArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItArchivoGuardarActionPerformed
        etiqHolaMundo.setText("Has guardado un archivo, ¡¡¡Muy bien!!!");
    }//GEN-LAST:event_menuItArchivoGuardarActionPerformed

    private void menuItSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItSalirAplicacionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItSalirAplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HolaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JLabel etiqHolaMundo;
    private javax.swing.JButton jButPulsa;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuItArchivoAbrir;
    private javax.swing.JMenuItem menuItArchivoGuardar;
    private javax.swing.JMenuItem menuItArchivoNuevo;
    private javax.swing.JMenuItem menuItSalirAplicacion;
    // End of variables declaration//GEN-END:variables
}
